"""fresh_start newfix

Revision ID: 0d019eb9e91e
Revises: 8d3aa74a16ce
Create Date: 2025-07-22 17:52:28.366578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d019eb9e91e'
down_revision: Union[str, None] = '8d3aa74a16ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uc_comment_like_user_comment', 'comment_likes', ['user_id', 'comment_id'])
    # op.create_unique_constraint('uc_reply_like_user_reply', 'comment_reply_likes', ['user_id', 'reply_id'])
    # op.create_unique_constraint('uc_like_user_event', 'event_likes', ['user_id', 'event_id'])
    # op.create_unique_constraint('uc_feature_vote_user_feature', 'feature_votes', ['user_id', 'feature_id'])
    # op.create_unique_constraint('uc_match_participant', 'match_participants', ['match_id', 'user_id'])
    # op.create_unique_constraint('uc_rsvp_user_event', 'rsvps', ['user_id', 'event_id'])
    op.create_foreign_key(None, 'users', 'invitation_tokens', ['invitation_token_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    # op.drop_constraint('uc_rsvp_user_event', 'rsvps', type_='unique')
    # op.drop_constraint('uc_match_participant', 'match_participants', type_='unique')
    # op.drop_constraint('uc_feature_vote_user_feature', 'feature_votes', type_='unique')
    # op.drop_constraint('uc_like_user_event', 'event_likes', type_='unique')
    # op.drop_constraint('uc_reply_like_user_reply', 'comment_reply_likes', type_='unique')
    # op.drop_constraint('uc_comment_like_user_comment', 'comment_likes', type_='unique')
    # ### end Alembic commands ###
