"""update_event_date_and_location_fields

Revision ID: 156408afd48b
Revises: 3d6c6de6fd19
Create Date: 2025-04-21 17:33:33.792901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '156408afd48b'
down_revision: Union[str, None] = '3d6c6de6fd19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('events', sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('events', sa.Column('start_time', sa.String(), nullable=True))
    op.add_column('events', sa.Column('end_time', sa.String(), nullable=True))
    op.add_column('events', sa.Column('all_day', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('venue_name', sa.String(), nullable=True))
    op.add_column('events', sa.Column('address', sa.String(), nullable=True))
    op.drop_column('events', 'location')
    op.drop_column('events', 'event_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('events', 'address')
    op.drop_column('events', 'venue_name')
    op.drop_column('events', 'all_day')
    op.drop_column('events', 'end_time')
    op.drop_column('events', 'start_time')
    op.drop_column('events', 'end_date')
    op.drop_column('events', 'start_date')
    # ### end Alembic commands ###
