"""removed votes

Revision ID: 34c0026c3433
Revises: 3f36d4626441
Create Date: 2025-04-03 17:59:56.686095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c0026c3433'
down_revision: Union[str, None] = '3f36d4626441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.add_column('invitation_tokens', sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('invitation_tokens', sa.Column('session_token', sa.String(), nullable=True))
    op.alter_column('invitation_tokens', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('invitation_tokens', 'is_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation_tokens', sa.Column('is_used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.alter_column('invitation_tokens', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('invitation_tokens', 'session_token')
    op.drop_column('invitation_tokens', 'usage_count')
    op.create_table('votes',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='votes_post_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='votes_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name='votes_pkey')
    )
    # ### end Alembic commands ###
