"""location simpler

Revision ID: 461501488e5e
Revises: c7d91d86123f
Create Date: 2025-07-07 15:07:45.949535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '461501488e5e'
down_revision: Union[str, None] = 'c7d91d86123f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('events', 'location',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'location',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('events', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###
