"""add_user_invitation_relationship

Revision ID: c86c5f530549
Revises: 156408afd48b
Create Date: 2025-04-28 07:51:42.570134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86c5f530549'
down_revision: Union[str, None] = '156408afd48b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invitation_token_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'invitation_tokens', ['invitation_token_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'invitation_token_id')
    # ### end Alembic commands ###
