"""Events model update update

Revision ID: cfb2cea3dc5c
Revises: 21d902d07e3c
Create Date: 2025-05-04 14:51:50.483010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb2cea3dc5c'
down_revision: Union[str, None] = '21d902d07e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('place', sa.String(), nullable=False))
    op.drop_column('events', 'venue_name')
    op.drop_column('events', 'all_day')
    op.drop_column('events', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('all_day', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('venue_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('events', 'place')
    # ### end Alembic commands ###
